openapi: 3.0.0
info:
  title: Incident Report API
  description: An API for incident reports for insurance clients.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Main (production) server
  - url: http://localhost:3000/api/v1
    description: Internal development server for local testing
tags:
  - name: incident
    description: Incident report

paths:
  /incident:
    post:
      tags:
        - incident
      operationId: incident report
      summary: incident report for insurance client
      description: incident report for insurance client
      requestBody:
        description: incident report for insurance client
        content:
          application/json:
            schema:
              type: object
              properties:
                incident:
                  type: string
                  description: incident
                  example: it is sunny today
                city:
                  type: string
                  description: city
                  example: Accra
                country:
                  type: string
                  description: country
                  example: Ghana
      responses:
        '201':
          description: A successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: success
                    example: success
                  data:
                    type: object
                    description: data
                    properties:
                      message: 
                        type: string
                        description: message
                        example: Incident report successfully posted
                      clientId:
                        type: integer
                        description: client id 
                        example: 10
                      incident:
                        type: string
                        description: incident
                        example: It is sunny today
                      city:
                        type: string
                        description: city
                        example: Accra
                      country:
                        type: string
                        description: country
                        example: Ghana
                      date:
                        type: string
                        description: date request was made
                        format: "Year-Month-Day"
                        example: "2022-12-13"
                      weatherReport:
                        type: object
                        description: weather report 
                        example: 
                          data:
                              coord:
                                lon: -0.2012
                                lat: 5.5571
                              weather: 
                                  id: 800,
                                  main: "Clear"
                                  description: "clear sky"
                                  icon: "01d"
                              base: "stations"
                              main:
                                temp: 300.83
                                feels_like: 303.57
                                temp_min: 300.83
                                temp_max: 300.83
                                pressure: 1013
                                humidity: 73
                                sea_level: 1013
                                grnd_level: 1009
                              visibility: 10000
                              wind:
                                speed: 2.65
                                deg: 246
                                gust: 2.61
                              clouds: 
                                all: 5
                              dt: 1670922768
                              sys: 
                                country: "GH"
                                sunrise: 1670911255
                                sunset: 1670953747
                              timezone: 0
                              id: 2306104,
                              name: "Accra"
                              cod: 200
      security:
        - bearerAuth: []  